---
title: "Cameroon plaque taxonomy analysis - Kraken RefSeq database to compare plaque vs other oral sites"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
    github_document:
        fig_width: 8
        fig_height: 6
        toc: true
---

```{r load_libraries, echo = F, message = F}
library(knitr)
library(data.table)
library(janitor)
library(mixOmics)
library(tidyverse)
library(viridis)
library(cowplot)
opts_chunk$set(echo=F, warning=F, message=F, dpi=150)
```

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("."))
```


```{r load_standard_report_data}

# for the Lassalle2017 and hmp2012 non-plaque oral samples
rso_report_nonpq_list <- list.files(path = "./report/", pattern = ".report.rso.kraken", full.names = T)
rso_reports_nonpq <- map_dfr(rso_report_nonpq_list, function(fn) {
  fread(fn, col.names = c("Percent", "Number_rooted", "Number_direct","Rank","NCBItaxID","SciName"), sep = "\t") %>%
  mutate(SampleID = basename(fn))
})


```

Read in the saved tables from `Cameroon_kraken_RSPM_add_taxonomy.Rmd` with CMC and Clemente2015 data
```{r}

# this takes several minutes, they're large files (~200MB)
# rso_reports <- fread("~/projects1/microbiome_calculus/Cameroon_plaque/00-documentation.backup/over100MB/kraken_standard_rso_reports.tsv")

# created by running `grep -v ".report.2.rso.kraken" /projects1/microbiome_calculus/Cameroon_plaque/00-documentation.backup/over100MB/kraken_standard_rso_reports.tsv | grep -v ".report.3.rso.kraken" > kraken_standard_rso_reports_run1.tsv`
rso_reports <- fread("~/projects1/users/velsko/oral_non_plaque/kraken/kraken_standard_rso_reports_run1.tsv")
rso_reports$SampleID <- gsub(".kraken","", rso_reports$SampleID)

rso_reports <- rso_reports %>% as_tibble() %>%
  separate(col = "SampleID", into = c("SampleID","Run"), sep = "\\.report\\.") %>%
  separate(col = "Run", into =c("Run","Database"), sep = "\\.")

```


```{r}

# convert to standard species tables
rso_reports_nonpq_df <- rso_reports_nonpq %>%
  mutate(SampleID = str_replace_all(SampleID, ".report.rso.kraken","")) %>%
  select(SampleID, NCBItaxID, Number_rooted, Rank) %>%
  filter(Rank == "S") %>%
  select(-Rank) %>%
  spread(SampleID, Number_rooted, fill = 0) %>%
  adorn_totals(where = "col") %>%
  mutate(Percent = Total / sum(Total)) %>%
  filter(Percent >= 0.0001) %>%
  select(-c("Total","Percent"))
 
rso_reports_df <- rso_reports %>%
  select(SampleID, NCBItaxID, Number_rooted, Rank) %>%
  filter(Rank == "S") %>%
  filter(!str_detect(SampleID, "CMC002.B0201|CMC032.B0101|CMC037.B0201|CMC047.A0201")) %>%
  select(-Rank) %>%
  spread(SampleID, Number_rooted, fill = 0) %>%
  adorn_totals(where = "col") %>%
  mutate(Percent = Total / sum(Total)) %>%
  filter(Percent >= 0.0001) %>%
  select(-c("Total","Percent"))
 

# and merge the tables together
kraken_otu <- rso_reports_nonpq_df %>%
  full_join(., rso_reports_df) %>%
  replace(is.na(.), 0)

# get the taxIDs and species names togeter for ros
reports_df_species <- rso_reports %>%
  select(SciName,NCBItaxID, Rank) %>%
  filter(Rank == "S") %>%
  select(SciName,NCBItaxID) %>%
  bind_rows(., rso_reports_nonpq %>%
            select(SciName, NCBItaxID, Rank) %>%
            filter(Rank == "S") %>%
            select(SciName,NCBItaxID)) %>%
  distinct()


```

Read in metadata for plotting
```{r}
oral_nonpq_metadata <- fread("~/projects1/users/velsko/oral_non_plaque/oral_nonpq_metadata.tsv")

oral_nonpq_metadata <- oral_nonpq_metadata %>% 
  mutate(Full = fct_relevel(Full, "Plaque - Industrial","Plaque - Non-industrial","Buccal mucosa - Industrial","Buccal mucosa - Non-industrial","Saliva - Industrial","Saliva - Non-industrial"))

```

Make a PCA plot
```{r}
# prep the table for input to PCA
kraken_otu_df <- kraken_otu %>%
  inner_join(., reports_df_species, by = "NCBItaxID") %>%
  select(SciName, everything()) %>%
  select(-NCBItaxID) %>%
  gather("SampleID","Counts",2:ncol(.)) %>%
  mutate(Counts = Counts + 1) %>%
  spread(SciName,Counts) %>%
  column_to_rownames("SampleID")

kraken_otu.pca <- mixOmics::pca(kraken_otu_df, ncomp = 3, logratio = 'CLR')
plot(kraken_otu.pca)

# Select out the PC variates into a new table and add the metadata for plotting
kraken_otu.pca.variates <- as.data.frame(kraken_otu.pca$variates$X)
kraken_otu.pca.variates <- kraken_otu.pca.variates %>%
  rownames_to_column("Library_ID")

kraken_otu.pca.varmet <- inner_join(kraken_otu.pca.variates, oral_nonpq_metadata, by = "Library_ID")

oral_non_pq_pc12 <- kraken_otu.pca.varmet %>%
  ggplot(., aes(PC1, PC2, colour = Full, shape = Full)) +
    geom_point(size = 3) +
    scale_shape_manual(values = c(1,16,2,17,0,15)) +
    scale_color_manual(values = c("#FF3200","#FF3200","#ff00cd","#ff00cd","#00cdff","#00cdff")) +
    xlab(paste("PC1 - ", 100*(round(kraken_otu.pca$explained_variance[1], 2)), "%", sep = "")) +
    ylab(paste("PC2 - ", 100*(round(kraken_otu.pca$explained_variance[2], 2)), "%", sep = "")) +
    theme_minimal(base_size = 14) +
    labs(color = "Source", shape = "Source") +
    theme(legend.title = element_text(size = 10))
oral_non_pq_pc12
# ggsave("~/Dropbox (Personal)/MPI-SHH/git-projects/Cameroon_plaque/06-publication/main_figures/Figure_XX1/panel_parts/SXX1_oral_non_pq_pc12.pdf", plot = oral_non_pq_pc12, device = "pdf",
#        scale = 1, width = 10, height = 4, units = c("in"), dpi = 300)
# ggsave("~/Dropbox (Personal)/MPI-SHH/git-projects/Cameroon_plaque/06-publication/main_figures/Figure_XX1/panel_parts/SXX1_oral_non_pq_pc12.png", plot = oral_non_pq_pc12, device = "png",
#        scale = 1, width = 10, height = 4, units = c("in"), dpi = 300)


```
























