---
title: "Cameroon hunter-gatherer calculus/plaque MALT alpha diversity"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
    github_document:
        fig_width: 8
        fig_height: 6
        toc: true
---

```{r load_libraries, echo = F, message = F}
library(knitr)
library(data.table)
library(rstatix)
library(vegan)
library(compositions)
library(janitor)
library(ggheatmap)
library(tidyverse)
library(gplots)
library(cowplot)
opts_chunk$set(echo=F, warning=F, message=F, dpi=150)
```

Set the working directory of the notebook to the parent directory of the 
notebook itself.

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

```{r load_data}

# load the taxonomy tables that have been decontaminated and the column headers are cleaned up
load("./05-results.backup/CMC_taxonomy_tables.RData")

# load the metadata file
load("./05-results.backup/CMC_metadata.RData")

# load the metadata file again with limited factors 
metadata_factors <- fread("./00-documentation.backup/01-cameroon_hunter_gatherer_metadata.tsv") %>%
  rename(SampleID = `#SampleID`) %>%
  mutate(Age_group = fct_relevel(Age_group, "10-18","18-29","30-39","40-49","50-59","60+","HMP","HMP10M"),
         Ethnic_Group = fct_relevel(Ethnic_Group, "Baka","Nzime","Yanomami","Industrial plaque","Industrial calculus","JAE10M",
                                     "ExtractionGauze","ExtractionBlank","LibraryBlank"),
         Env = fct_relevel(Env, "CMC","Industrial plaque","Industrial calculus",
                                     "ExtractionGauze","ExtractionBlank","LibraryBlank"),
         Market_integration = fct_relevel(Market_integration, "Logging road","Forrest camp","Farming","Yanomami",
                                      "Industrial","ExtractionGauze","ExtractionBlank","LibraryBlank"),
         Market_integration_split = fct_relevel(Market_integration_split, "Forrest camp","Logging road","Farming","Yanomami",
                                      "Industrial plaque","Industrial calculus", "ExtractionGauze","ExtractionBlank","LibraryBlank"),
         Sex = fct_relevel(Sex, "Female","Male"),
         Tooth_site = fct_relevel(Tooth_site, "Anterior","Posterior","Buccal_mucosa","HMP","HMP10M"),
         Type = fct_relevel(Type, "Calculus","Plaque","Blank"),
         Village = fct_relevel(Village, "202","205","204","203","206","Industrial plaque","Industrial calculus",
                               "ExtractionGauze","ExtractionBlank","LibraryBlank"))

```

```{r phylum_table}
phylum <- fread("./05-results.backup/MALT_all_data_combined_phylum.tsv") %>%
  rename(Phylum = 1) %>%
  select(-matches("VLC")) %>%
  full_join(., fread("./05-results.backup/Iberian_samples-controls_phylum.tsv") %>%
              rename(Phylum = 1) %>%
              select(matches("Phylum|VLC|SRR")), by = "Phylum") %>%
  pivot_longer(!Phylum, names_to = "SampleID", values_to = "Counts") %>%
  mutate(SampleID = str_replace_all(SampleID, ".SG1.unmapped",""),
         SampleID = str_replace_all(SampleID, ".unmapped",""))  %>%
  pivot_wider(names_from = "SampleID", values_from = "Counts")


```


```{r}
# load the metadata file again without factors for stats
# so don't have extra unnecessary categories with factors
metadata_nofactors <- fread("./00-documentation.backup/01-cameroon_hunter_gatherer_metadata.tsv") %>%
  rename(SampleID = `#SampleID`)

# set limited colors w/o extra groups
Age_group_colors <- c(`18-29` = "#FF3200", `30-39` = "#E9B186", `40-49` = "#82CDAA", `50-59` = "#0686B8", `60+` = "#172869")
Age_group_shapes <- c(`18-29` = 15, `30-39` = 16, `40-49` = 17, `50-59` = 18, `60+` = 25)
Env_colors <- c(CMC = "#FF3200", `Industrial plaque` = "#969696", `Industrial calculus` = "#feb24c",  ExtractionGauze = "#252525", ExtractionBlank = "#737373", LibraryBlank = "#bdbdbd")
Env_shapes <- c(CMC = 19, HMP = 7, JAE = 7, ExtractionGauze = 8, ExtractionBlank = 4, LibraryBlank = 3)
Ethnic_Group_shapes <- c(Baka = 19, Nzime = 17,  Yanomami = 14, `Industrial plaque` = 7, `Industrial calculus` = 7)
Ethnic_Group_colors <- c(Baka = "#FF3200", Nzime = "#065FA3", `Industrial plaque` = "#969696", `Industrial calculus` = "#feb24c")
Market_integration_colors <- c(`Logging road` = "#FF3200", `Forrest camp` = "#065FA3", Farming = "#82CDAA")
Market_integration_shapes <- c(`Logging road` = 19, `Forrest camp` = 17, Farming = 18, Industrial = 15)
Village_colors <- c(`202` = "#FF3200", `205` = "#EF8158", `204` = "#E9BD8E", `203` = "#CBDDA7", `206` = "#38BCAD", `Industrial plaque` = "#969696", `Industrial calculus` = "#feb24c", ExtractionGauze = "#252525", ExtractionBlank = "#737373", LibraryBlank = "#bdbdbd")
Village_shapes <- c(`202` = 15, `203` = 16, `205` = 17,`204` = 18, `206` = 25, `Industrial plaque` = 7, `Industrial calculus` = 7)
Sex_colors <- c(Female = "#FF3200", Male = "#065FA3")
Sex_shapes <- c(Female = 19, Male = 17)
Tooth_site_colors <- c(Anterior = "#FF3200", Posterior = "#065FA3")
Tooth_site_shapes <- c(Anterior = 19, Posterior = 17)

```

## Bacteroidetes/Firmicutes
```{r}

phylum %>%
  as_tibble() %>%
  adorn_percentages(denominator = "col") %>%
  pivot_longer(!Phylum, names_to = "SampleID", values_to = "Percent") %>%
  pivot_wider(names_from = "Phylum", values_from = "Percent") %>%
  mutate(BF_ratio = Bacteroidetes / Firmicutes) %>%
  select(matches("Sample|BF_ratio")) %>%
  inner_join(., metadata %>%
               select(SampleID, Market_integration_split, Village, Tooth_site, Env), by = "SampleID") %>%
  filter(str_detect(Env, "CMC|plaque|calculus")) %>%
  ggplot(., aes(x = Market_integration_split, y = BF_ratio, fill = Market_integration_split)) +
    geom_boxplot(color = "black", size = 0.2) +
    geom_point(alpha = 0.3, size = 0.8) +
    theme_minimal() +
    scale_fill_manual(values = Market_integration_split_colors) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
    xlab("Market integration") +
    ylab("Bacteriodetes:Firmicutes")

```

```{r}

phylum %>%
  as_tibble() %>%
  adorn_percentages(denominator = "col") %>%
  pivot_longer(!Phylum, names_to = "SampleID", values_to = "Percent") %>%
  pivot_wider(names_from = "Phylum", values_from = "Percent") %>%
  mutate(BF_ratio = Bacteroidetes / Firmicutes) %>%
  select(matches("Sample|BF_ratio")) %>%
  inner_join(., metadata %>%
               select(SampleID, Market_integration_split, Village, Tooth_site, Env), by = "SampleID") %>%
  filter(str_detect(Env, "CMC|plaque|calculus")) %>%
ggplot(., aes(x = Market_integration_split, y = BF_ratio, fill = Market_integration_split)) + 
  ## add half-violin from {ggdist} package
  ggdist::stat_halfeye(
    ## custom bandwidth
    adjust = .5, 
    ## adjust height
    width = .6, 
    ## move geom to the right
    justification = -.2, 
    ## remove slab interval
    .width = 0, 
    point_colour = NA
  ) + 
  geom_boxplot(
    width = .12, 
    ## remove outliers
    outlier.color = NA, ## `outlier.shape = NA` works as well
    color = "grey30"
  ) +
  ## add dot plots from {ggdist} package
  ggdist::stat_dots(
    ## orientation to the left
    side = "left", 
    ## move geom to the left
    justification = 1.1, 
    ## adjust grouping (binning) of observations 
    binwidth = 0.1
  ) + 
  ## remove white space on the left
coord_cartesian(xlim = c(1.2, NA)) +
  theme_minimal(base_size = 14) +
  scale_fill_manual(values = Market_integration_split_colors) +
  theme(axis.text = element_text(size = 14)) +
  theme(legend.position = "none") +
  xlab("Market integration") +
  ylab("Bacteroidetes:Firmicutes ratio") +
  theme(axis.title.x = element_text(vjust=-1.5)) +
  theme(axis.title.y = element_text(vjust=1.9))


```

```{r}
# test for significant differences between market integration groups
phylum %>%
  as_tibble() %>%
  adorn_percentages(denominator = "col") %>%
  pivot_longer(!Phylum, names_to = "SampleID", values_to = "Percent") %>%
  pivot_wider(names_from = "Phylum", values_from = "Percent") %>%
  mutate(BF_ratio = Bacteroidetes / Firmicutes) %>%
  select(matches("Sample|BF_ratio")) %>%
  inner_join(., metadata %>%
               select(SampleID, Market_integration_split, Village, Tooth_site, Env), by = "SampleID") %>%
  filter(str_detect(Env, "CMC|plaque|calculus")) %>%
  mutate(Market_integration_split = as.character(Market_integration_split)) %>%
  select(SampleID, BF_ratio, Market_integration_split) %>%
  rstatix::wilcox_test(BF_ratio ~ Market_integration_split, p.adjust.method = "fdr")

# test for significant differences between tooth sites within market integration groups
phylum %>%
  as_tibble() %>%
  adorn_percentages(denominator = "col") %>%
  pivot_longer(!Phylum, names_to = "SampleID", values_to = "Percent") %>%
  pivot_wider(names_from = "Phylum", values_from = "Percent") %>%
  mutate(BF_ratio = Bacteroidetes / Firmicutes) %>%
  select(matches("Sample|BF_ratio")) %>%
  inner_join(., metadata %>%
               select(SampleID, Market_integration_split, Village, Tooth_site, Env), by = "SampleID") %>%
  filter(str_detect(Env, "CMC|plaque|calculus")) %>%
  mutate(Market_integration_split = as.character(Market_integration_split),
         Tooth_site = as.character(Tooth_site),
         Village = as.character(Village)) %>%
  filter(!str_detect(Env, "Industrial")) %>%
  mutate(Tooth_site = ifelse(str_detect(Village, "Industrial"), Village, Tooth_site)) %>%
  select(SampleID, BF_ratio, Market_integration_split, Tooth_site) %>%
  group_by(Market_integration_split) %>%
  rstatix::wilcox_test(BF_ratio ~ Tooth_site, p.adjust.method = "fdr")
  
```
```{r effect_size}
phylum %>%
  as_tibble() %>%
  adorn_percentages(denominator = "col") %>%
  pivot_longer(!Phylum, names_to = "SampleID", values_to = "Percent") %>%
  pivot_wider(names_from = "Phylum", values_from = "Percent") %>%
  mutate(BF_ratio = Bacteroidetes / Firmicutes) %>%
  select(matches("Sample|BF_ratio")) %>%
  inner_join(., metadata %>%
               select(SampleID, Market_integration_split, Village, Tooth_site, Env), by = "SampleID") %>%
  filter(str_detect(Env, "CMC|plaque|calculus")) %>%
  mutate(Market_integration_split = as.character(Market_integration_split)) %>%
  select(SampleID, BF_ratio, Market_integration_split) %>%
  rstatix::wilcox_effsize(BF_ratio ~ Market_integration_split, p.adjust.method = "fdr")

phylum %>%
  as_tibble() %>%
  adorn_percentages(denominator = "col") %>%
  pivot_longer(!Phylum, names_to = "SampleID", values_to = "Percent") %>%
  pivot_wider(names_from = "Phylum", values_from = "Percent") %>%
  mutate(BF_ratio = Bacteroidetes / Firmicutes) %>%
  select(matches("Sample|BF_ratio")) %>%
  inner_join(., metadata %>%
               select(SampleID, Market_integration_split, Village, Tooth_site, Env), by = "SampleID") %>%
  filter(str_detect(Env, "CMC|plaque|calculus")) %>%
  mutate(Market_integration_split = as.character(Market_integration_split),
         Tooth_site = as.character(Tooth_site),
         Village = as.character(Village)) %>%
  filter(!str_detect(Env, "Industrial")) %>%
  mutate(Tooth_site = ifelse(str_detect(Village, "Industrial"), Village, Tooth_site)) %>%
  select(SampleID, BF_ratio, Market_integration_split, Tooth_site) %>%
  group_by(Market_integration_split) %>%
  rstatix::wilcox_effsize(BF_ratio ~ Tooth_site, p.adjust.method = "fdr")

```


## Prevotella/Bacteroidetes (Bacteroides?)
```{r prev_bact_heat_map}

# make a table of just Prevotella/Bacterioidetes/Phocaeicola
malt_species.decontam_pb <- malt_species.decontam %>%
  select(-matches("ERR|SRS|SRR164|EXB|LIB")) %>%
  # leave the space in the Pevotella part to make sure other names with Prevotella aren't included
  filter(str_detect(Species, "Prevotella |Phocaeicola|Bacteroidetes|Bacteroides")) %>%
  # remove any species that don't have any counts in these samples
  adorn_totals(where = "col") %>%
  filter(Total != 0) %>%
  select(-Total) %>%
  # Bacteroidetes oral taxon 274 has finally been renamed Phocaeicola abscessus in HOMD
  mutate(Species = str_replace(Species, "Bacteroidetes oral taxon 274", "Phocaeicola abscessus")) %>%
  pivot_longer(!Species, names_to = "Sample_ID", values_to = "Counts") %>%
  # merge counts for the 2 Phocaeicola abscessus entries
  group_by(Species, Sample_ID) %>%
  summarize(Total = sum(Counts)) %>%
  rename(Counts = Total) %>%
  ungroup() %>%
  # add 1 for a CLR-transform
  mutate(Counts = Counts + 1) %>%
  pivot_wider(names_from = "Sample_ID", values_from = "Counts")%>%
  column_to_rownames("Species")

```

```{r}
# genus-level proportions

malt_genus <- fread("./05-results.backup/MALT_all_data_combined_Comparison_genus_names.tsv") %>%
  rename(Species = `#Datasets`)

malt_genus_contaminants <- fread("./05-results.backup/malt_contaminants_genus.tsv")

malt_genus_decontam <- malt_genus %>%
  anti_join(., malt_genus_contaminants) %>%
  rename(Genus = Species) %>%
  filter(!str_detect(Genus, "Homo|Not assigned")) %>%
  select(-matches("VLC")) %>%
  # remove extra samples from Clemente study (these might be industrial samples) 
  select(-matches("SRR1646026|SRR1646027|SRR1646028|SRR1646029|SRR1646034|SRR1646035|SRR1646036|SRR1646037"))

# now get the missing data from 
malt_missed_table <- fread("./00-documentation.backup/Iberian_samples-controls_comparison-genus.tsv") %>%
  select(matches("Data|JAE014|JAE015|VLC|SRR061192|SRR061294|SRR061320|SRR061365|SRR061562|SRR062083|SRR062298|SRR062299|SRR063517|SRR1804664|SRR1804823|SRR512767|SRR513165|SRR513768|SRR513775|SRR513828|SRR514202|SRR514239|SRR514306|SRR514329")) %>%
  rename(Genus = `#Datasets`) %>%
  filter(!str_detect(Genus, "Homo|Not assigned"))

malt_genus_decontam <- malt_genus_decontam %>%
  select(-matches("ERR|SRS|SRR164|EXB|LIB|VLC")) %>%
  # add the missing data
  full_join(., malt_missed_table, by = "Genus")

```

```{r}
malt_genus_decontam %>%
  # convert to percentages, where the samples total 1 (samples are columns, species are rows)
  adorn_percentages(denominator = "col") %>%
  # select the 3 genera of interest 
  filter(str_detect(Genus, "Prevotella|Phocaeicola|Bacteroides"),
         Genus != "Prevotellamassilia") %>%
  pivot_longer(!Genus, names_to = "Library_ID", values_to = "Proportion") %>%
  mutate(Library_ID = str_replace_all(Library_ID, ".SG1.unmapped",""),
         Library_ID = str_replace_all(Library_ID, ".unmapped",""),
         Library_ID = str_replace_all(Library_ID, "-1","")) %>%
  left_join(., metadata %>%
              rename(Library_ID = SampleID) %>%
              select(Library_ID, Env)) %>%
  group_by(Env, Genus) %>%
  summarize(Mean_prop = mean(Proportion)) %>%
  ungroup() %>%
  # mutate(Env = fct_relevel(Env, "Non-industrial plaque", "Industrial calculus", "Industrial plaque")) %>%
  arrange(Env) %>%
  ggplot(., aes(x = Env, y = Mean_prop, fill = Genus)) +
    geom_bar(stat = "identity", position = position_dodge()) +
    theme_minimal() +
    scale_fill_manual(values = c("#FF3200","#065FA3","#FEB24C")) +
    ylab("Mean proportion")


```

```{r}

malt_genus_decontam %>%
  # convert to percentages, where the samples total 1 (samples are columns, species are rows)
  adorn_percentages(denominator = "col") %>%
  # select the 3 genera of interest 
  filter(str_detect(Genus, "Prevotella|Phocaeicola|Bacteroides"),
         Genus != "Prevotellamassilia") %>%
  pivot_longer(!Genus, names_to = "Library_ID", values_to = "Proportion") %>%
  mutate(Library_ID = str_replace_all(Library_ID, ".SG1.unmapped",""),
         Library_ID = str_replace_all(Library_ID, ".unmapped",""),
         Library_ID = str_replace_all(Library_ID, "-1","")) %>%
  pivot_wider(names_from = "Genus", values_from = "Proportion") %>%
  mutate(PB_ratio = Prevotella / Bacteroides) %>%
  left_join(., metadata %>%
              rename(Library_ID = SampleID) %>%
              select(Library_ID, Market_integration_split)) %>%
  mutate(PB_ratio = ifelse(is.infinite(PB_ratio),500,PB_ratio)) %>% # fill with the highest ratio value
ggplot(., aes(x = Market_integration_split, y = PB_ratio, fill = Market_integration_split)) + 
  ## add half-violin from {ggdist} package
  ggdist::stat_halfeye(
    ## custom bandwidth
    adjust = .5, 
    ## adjust height
    width = .6, 
    ## move geom to the right
    justification = -.2, 
    ## remove slab interval
    .width = 0, 
    point_colour = NA
  ) + 
  geom_boxplot(
    width = .12, 
    ## remove outliers
    outlier.color = NA, ## `outlier.shape = NA` works as well
    color = "grey30"
  ) +
  ## add dot plots from {ggdist} package
  ggdist::stat_dots(
    ## orientation to the left
    side = "left", 
    ## move geom to the left
    justification = 1.1, 
    ## adjust grouping (binning) of observations 
    binwidth = 11
  ) + 
  ## remove white space on the left
coord_cartesian(xlim = c(1.2, NA)) +
  theme_minimal(base_size = 14) +
  scale_fill_manual(values = Market_integration_split_colors) +
  theme(axis.text = element_text(size = 14)) +
  theme(legend.position = "none") +
  xlab("Market integration") +
  ylab("Prevotella:Bacteroides ratio") +
  theme(axis.title.x = element_text(vjust=-1.5)) +
  theme(axis.title.y = element_text(vjust=1.9))


```

```{r}
# test for significant differences between market integration groups
malt_genus_decontam %>%
  # convert to percentages, where the samples total 1 (samples are columns, species are rows)
  adorn_percentages(denominator = "col") %>%
  # select the 3 genera of interest 
  filter(str_detect(Genus, "Prevotella|Phocaeicola|Bacteroides"),
         Genus != "Prevotellamassilia") %>%
  pivot_longer(!Genus, names_to = "Library_ID", values_to = "Proportion") %>%
  mutate(Library_ID = str_replace_all(Library_ID, ".SG1.unmapped",""),
         Library_ID = str_replace_all(Library_ID, ".unmapped",""),
         Library_ID = str_replace_all(Library_ID, "-1","")) %>%
  pivot_wider(names_from = "Genus", values_from = "Proportion") %>%
  mutate(PB_ratio = Prevotella / Bacteroides) %>%
  left_join(., metadata %>%
              rename(Library_ID = SampleID) %>%
              select(Library_ID, Market_integration_split)) %>%
  filter(!is.infinite(PB_ratio))%>% # remove all Inf entries
  mutate(Market_integration_split = as.character(Market_integration_split)) %>%
  select(Library_ID, PB_ratio, Market_integration_split) %>%
  rstatix::pairwise_wilcox_test(PB_ratio ~ Market_integration_split, p.adjust.method = "fdr") %>%
  arrange(p.adj)

# test for significant differences between tooth sites within market integration groups
malt_genus_decontam %>%
  # convert to percentages, where the samples total 1 (samples are columns, species are rows)
  adorn_percentages(denominator = "col") %>%
  # select the 3 genera of interest 
  filter(str_detect(Genus, "Prevotella|Phocaeicola|Bacteroides"),
         Genus != "Prevotellamassilia") %>%
  pivot_longer(!Genus, names_to = "Library_ID", values_to = "Proportion") %>%
  mutate(Library_ID = str_replace_all(Library_ID, ".SG1.unmapped",""),
         Library_ID = str_replace_all(Library_ID, ".unmapped",""),
         Library_ID = str_replace_all(Library_ID, "-1","")) %>%
  pivot_wider(names_from = "Genus", values_from = "Proportion") %>%
  mutate(PB_ratio = Prevotella / Bacteroides) %>%
  left_join(., metadata %>%
              rename(Library_ID = SampleID) %>%
              select(Library_ID, Market_integration_split, Tooth_site, Village, Env)) %>%
  filter(!is.infinite(PB_ratio)) %>% # remove all Inf entries
  mutate(Market_integration_split = as.character(Market_integration_split),
         Tooth_site = as.character(Tooth_site),
         Village = as.character(Village)) %>%
  filter(!str_detect(Env, "Industrial")) %>%
  # mutate(Tooth_site = ifelse(str_detect(Village, "Industrial"))) %>%
  select(Library_ID, PB_ratio, Market_integration_split, Tooth_site) %>%
  group_by(Market_integration_split) %>%
  rstatix::pairwise_wilcox_test(PB_ratio ~ Tooth_site, p.adjust.method = "fdr") %>%
  arrange(p.adj)
  
```

```{r prev_bact_heat_map}
# CLR-transform the matrix for plotting the heatmap
malt_species.decontam_pb_clr <- clr(malt_species.decontam_pb)
malt_species.decontam_pb_clr <- as.matrix(malt_species.decontam_pb_clr)

# set the sample order for plotting
each_order <- metadata %>%
  select(SampleID, Env) %>%
  filter(!str_detect(SampleID, "ERR|SRS|SRR164|EXB|LIB")) %>%
  arrange(Env) %>%
  pull(SampleID)

malt_species.decontam_pb_clr_long <- malt_species.decontam_pb_clr %>%
  as.data.frame() %>%
  rownames_to_column("species") %>%
  pivot_longer(!species, names_to = "Sample_ID", values_to = "CLR") %>%
  mutate(Sample_ID = fct_relevel(Sample_ID, each_order)) # each_order from here, sample_order from Kraken_gtdb.Rmd

malt_species.decontam_pb_clr_long %>%
  arrange(Sample_ID) %>%
  ggplot(., aes(Sample_ID, species, fill = CLR)) +
    geom_tile() +
    scale_fill_viridis_c(option = "A") +
    theme_minimal(base_size = 14) +
    theme(axis.text.x = element_text(angle = 90, hjust = 0.95, vjust = 0.5),
          plot.margin = margin(0, 0, 0, 0, "pt"),
          axis.title.y = element_blank(),
          legend.position = "left")


```

```{r distance_calculations}

# orient the matrix with correct rows/columns to run the distance calculation for the species, not the samples 
# (need to have columns as Species, rows as Sample_ID)
malt_species.decontam_pb_clr_sp <- malt_species.decontam_pb_clr %>%
  as.data.frame()


# perform a distance calculation for hierarchical clustering for the species ordering
malt_species.decontam_pb_clr_dist <- vegdist(malt_species.decontam_pb_clr_sp, method = "euclidian")
# cluster the data with hclust
malt_species.decontam_pb_clr_dist_hr <- hclust(malt_species.decontam_pb_clr_dist)


```


```{r cluster_species}

# malt_species.decontam_pb_clr_dist_hr$order gives the dendrogram order from the bottom to the top, but using the row numbers not the row names
# pull this order out and store as a vector to make the order a factor in the next step for plotting
sp_each_order <- malt_species.decontam_pb_clr_dist_hr$order %>%
  as.character.numeric_version(.) %>%
  str_trim(.)

# use the dendrogram order to pull out the species in the correct order for the heatmap
malt_species.decontam_pb_clr_order <- malt_species.decontam_pb_clr %>%
  as.data.frame() %>%
  rownames_to_column("Species") %>%
  gather("SampleID","CLR",2:ncol(.)) %>%
  spread(SampleID,CLR) %>%
  mutate(SpOrder = as.character(seq(1,56))) %>%
  select(Species, SpOrder, everything()) %>%
  mutate(SpOrder = fct_relevel(SpOrder, sp_each_order)) %>%
  arrange(SpOrder) %>%
  pull(Species)

# make the species a factor so they're in the correct order for the heatmap using the vector from the step above
# malt_species.decontam_pb_clr_long_smp <- malt_species.decontam_pb_clr %>%
#   as.data.frame() %>%
#   rownames_to_column("Species") %>%
#   mutate(Species = fct_relevel(Species, malt_species.decontam_pb_clr_order)) %>%
#   arrange(Species) %>%
#   pivot_longer(!Species, names_to = "Sample_ID", values_to = "CLR")


```

```{r cluster_samples}

# now cluster by sample, need to transpose the input table to have columns as SampleID, rows as Species
# to custer by sample instead of species
# convert the matrix to a data.frame
malt_species.decontam_pb_clr_smp <- malt_species.decontam_pb_clr %>%
  as.data.frame() %>%
  rownames_to_column("Species") %>%
  pivot_longer(!Species, names_to = "Sample_ID", values_to = "CLR") %>%
  pivot_wider(names_from = "Species", values_from = "CLR") %>%
  column_to_rownames("Sample_ID")


# perform a distance calculation for hierarchical clustering for the species ordering
malt_species.decontam_pb_clr_smp_dist <- vegdist(malt_species.decontam_pb_clr_smp, method = "euclidian")
# cluster the data with hclust
malt_species.decontam_pb_clr_smp_dist_hr <- hclust(malt_species.decontam_pb_clr_smp_dist)
# malt_species.decontam_pb_clr_dist_hr$order gives the dendrogram order from the bottom to the top, but using the row numbers not the row names
# pull this order out and store as a vector to make the order a factor in the next step for plotting
smp_each_order <- malt_species.decontam_pb_clr_smp_dist_hr$order %>%
  as.character.numeric_version(.) %>%
  str_trim(.)

# use the dendrogram order to pull out the species in the correct order for the heatmap
malt_species.decontam_pb_clr_smp_order <- malt_species.decontam_pb_clr %>%
  as.data.frame() %>%
  rownames_to_column("Species") %>%
  pivot_longer(!Species, names_to = "Sample_ID", values_to = "CLR") %>%
  pivot_wider(names_from = "Species", values_from = "CLR") %>%
  mutate(SmpOrder = as.character(seq(1,122))) %>%  
  select(Sample_ID, SmpOrder, everything()) %>%
  mutate(SmpOrder = fct_relevel(SmpOrder, smp_each_order)) %>%
  arrange(SmpOrder) %>%
  pull(Sample_ID)



```

```{r pb_heatmap}
# Plot the heatmap with samples ordered by the clustering from above
# make the SampleIDs a factor so they're in the correct order for the heatmap using the vector from the step above

malt_species.decontam_pb_clr_long_smp <- malt_species.decontam_pb_clr %>%
  as.data.frame() %>%
  rownames_to_column("Species") %>%
  mutate(Species = fct_relevel(Species, malt_species.decontam_pb_clr_order)) %>%
  arrange(Species) %>%
  pivot_longer(!Species, names_to = "Sample_ID", values_to = "CLR") %>%
  mutate(Sample_ID = fct_relevel(Sample_ID, malt_species.decontam_pb_clr_smp_order))


vector_color = malt_species.decontam_pb_clr_long_smp %>%
  left_join(., metadata %>%
              rename(Sample_ID = SampleID) %>%
              select(Sample_ID, Env)) %>%
  mutate(Sample_ID = fct_relevel(Sample_ID, malt_species.decontam_pb_clr_smp_order)) %>%
  arrange(Sample_ID) %>%
  mutate(Color = ifelse(Env == "CMC", "#FF3200",
                        ifelse(Env == "Industrial calculus", "#feb24c", "#065FA3"))) %>%
  select(Sample_ID, Color) %>%
  unique %>%
  pull(Color) %>%
  as.character()


# make a heatmap with ggplot
malt_species.decontam_pb_clr_long_smp %>%
  ggplot(., aes(Sample_ID, Species, fill = CLR)) +
    geom_tile() +
    scale_fill_viridis_c(option = "A") +
    theme_minimal(base_size = 14) +
    theme(axis.text.x = element_text(angle = 90, hjust = 0.95, vjust = 0.5, color = vector_color),
          plot.margin = margin(0, 0, 0, 0, "pt"),
          axis.title.y = element_blank(),
          legend.position = "left")


```


























