---
title: "Cameroon hunter-gatherer calculus/plaque MALT differentially abundant taxa"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
    github_document:
        fig_width: 8
        fig_height: 6
        toc: true
---

```{r load_libraries, echo = F, message = F}
library(knitr)
library(data.table)
library(janitor)
library(pander)
library(tidyverse)
library(gplots)
library(viridis)
library(cowplot)
opts_chunk$set(echo=F, warning=F, message=F, dpi=150)
```

Set the working directory of the notebook to the parent directory of the 
notebook itself.  

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

```{r load_data}

# load the taxonomy tables that have been decontaminated and the column headers are cleaned up
load("./05-results.backup/CMC_taxonomy_tables.RData")

# load the metadata file
load("./05-results.backup/CMC_metadata.RData") # this sets the metadata as factors. Check if it works before deleting the commented out section below

metadata <- metadata %>%
  rename(Sample.ID = SampleID)  %>%
  as_data_frame() %>%
  select(`Sample.ID`, Description, Industry, Age_group, Env, Ethnic_Group, Market_economy, Sex, Tooth_site, Village)


# metadata <- fread("00-documentation.backup/01-cameroon_hunter_gatherer_metadata.tsv")
# metadata <- metadata %>%
#   rename(Sample.ID = `#SampleID`)  %>%
#   as_data_frame() %>%
#   select(`Sample.ID`, Description, Industry, Age_group, Env, Ethnic_Group, Market_economy, Sex, Tooth_site, Village)

```


List the outliers from the plot in section `raw_plot` in `Cameroon_h-g_taxonomy.Rmd` and remove them from the taxonomy table. 
```{r outliers}
outliers <- c("CMC002.B0201","CMC032.B0101","CMC037.B0201","CMC047.A0201",
              "EXB059.A1901","EXB059.A1301","EXB059.A1101","EXB059.A0901",
              "SRR1646041","SRR1646032","SRR1646042","SRR1646045","SRR1646030","SRR1646047")

outliersF <- str_c(outliers, collapse = "|")

```


```{r input_tables}
# species, no blanks 
malt_species.decontam_filtered_noblanks <- malt_species.decontam %>%
                                         select(-one_of(outliers)) %>%
                                         select(-starts_with("EXB")) %>%
                                         select(-starts_with("LIB")) %>%
                                         select(-contains("10M")) %>%
                                         adorn_totals(where = "col", name = "Sum_species") %>%
                                         mutate(Percent = Sum_species/sum(Sum_species)*100) %>%
                                         filter(Percent > 0.001) %>%
                                         select(-one_of(c("Sum_species","Percent"))) %>%
                                         gather("SampleID","Counts",2:ncol(.)) %>%
                                         spread(Species,Counts)

rownames(malt_species.decontam_filtered_noblanks) <- malt_species.decontam_filtered_noblanks$SampleID

malt_species.decontam_filtered_noblanks <- malt_species.decontam_filtered_noblanks %>% select(-SampleID)

malt_species.decontam_filtered_noblanks = malt_species.decontam_filtered_noblanks+1


# species, no blanks, no Yanomami
malt_species.decontam_filtered_noblanks_noyanomami <- malt_species.decontam %>%
                                         select(-one_of(outliers)) %>%
                                         select(-starts_with("EXB")) %>%
                                         select(-starts_with("LIB")) %>%
                                         select(-contains("10M")) %>%
                                         select(-starts_with("SRR16460")) %>%
                                         adorn_totals(where = "col", name = "Sum_species") %>%
                                         mutate(Percent = Sum_species/sum(Sum_species)*100) %>%
                                         filter(Percent > 0.001) %>%
                                         select(-one_of(c("Sum_species","Percent"))) %>%
                                         gather("SampleID","Counts",2:ncol(.)) %>%
                                         spread(Species,Counts)

rownames(malt_species.decontam_filtered_noblanks_noyanomami) <- malt_species.decontam_filtered_noblanks_noyanomami$SampleID

malt_species.decontam_filtered_noblanks_noyanomami <- malt_species.decontam_filtered_noblanks_noyanomami %>% select(-SampleID)

malt_species.decontam_filtered_noblanks_noyanomami = malt_species.decontam_filtered_noblanks_noyanomami+1


# species, CMC samples only
malt_species.decontam_filtered_cmc <- malt_species.decontam %>%
                                         select(-one_of(outliers)) %>%
                                         select(-starts_with("EXB")) %>%
                                         select(-starts_with("LIB")) %>%
                                         select(-starts_with("SRR")) %>%
                                         select(-starts_with("JAE")) %>%
                                         select(-contains("10M")) %>%
                                         adorn_totals(where = "col", name = "Sum_species") %>%
                                         mutate(Percent = Sum_species/sum(Sum_species)*100) %>%
                                         filter(Percent > 0.001) %>%
                                         select(-one_of(c("Sum_species","Percent"))) %>%
                                         gather("SampleID","Counts",2:ncol(.)) %>%
                                         spread(Species,Counts)

rownames(malt_species.decontam_filtered_cmc) <- malt_species.decontam_filtered_cmc$SampleID

malt_species.decontam_filtered_cmc <- malt_species.decontam_filtered_cmc %>% select(-SampleID)

malt_species.decontam_filtered_cmc = malt_species.decontam_filtered_cmc+1


# genus, no blanks
malt_genus.decontam_filtered <- malt_genus.decontam %>%
                                         select(-one_of(outliers)) %>%
                                         select(-starts_with("EXB")) %>%
                                         select(-starts_with("LIB")) %>%
                                         select(-contains("10M")) %>%
                                         adorn_totals(where = "col", name = "Sum_genus") %>%
                                         mutate(Percent = Sum_genus/sum(Sum_genus)*100) %>%
                                         filter(Percent > 0.01) %>%
                                         select(-one_of(c("Sum_genus","Percent"))) %>%
                                         gather("SampleID","Counts",2:ncol(.)) %>%
                                         spread(Species,Counts)

rownames(malt_genus.decontam_filtered) <- malt_genus.decontam_filtered$SampleID

malt_genus.decontam_filtered <- malt_genus.decontam_filtered %>% select(-SampleID)

malt_genus.decontam_filtered = malt_genus.decontam_filtered+1


# genus, no blanks, no Yanomami
malt_genus.decontam_filtered_noyanomami <- malt_genus.decontam %>%
                                         select(-one_of(outliers)) %>%
                                         select(-starts_with("EXB")) %>%
                                         select(-starts_with("LIB")) %>%
                                         select(-contains("10M")) %>%
                                         # select(-one_of(fullSRR)) %>%
                                         adorn_totals(where = "col", name = "Sum_genus") %>%
                                         mutate(Percent = Sum_genus/sum(Sum_genus)*100) %>%
                                         filter(Percent > 0.01) %>%
                                         select(-one_of(c("Sum_genus","Percent"))) %>%
                                         gather("SampleID","Counts",2:ncol(.)) %>%
                                         spread(Species,Counts)

rownames(malt_genus.decontam_filtered_noyanomami) <- malt_genus.decontam_filtered_noyanomami$SampleID

malt_genus.decontam_filtered_noyanomami <- malt_genus.decontam_filtered_noyanomami %>% select(-SampleID)

malt_genus.decontam_filtered_noyanomami = malt_genus.decontam_filtered_noyanomami+1


# genus, CMC samples only
malt_genus.decontam_filtered_cmc <- malt_genus.decontam %>%
                                         select(-one_of(outliers)) %>%
                                         select(-starts_with("EXB")) %>%
                                         select(-starts_with("LIB")) %>%
                                         select(-starts_with("SRR")) %>%
                                         select(-starts_with("JAE")) %>%
                                         adorn_totals(where = "col", name = "Sum_genus") %>%
                                         mutate(Percent = Sum_genus/sum(Sum_genus)*100) %>%
                                         filter(Percent > 0.001) %>%
                                         select(-one_of(c("Sum_genus","Percent"))) %>%
                                         gather("SampleID","Counts",2:ncol(.)) %>%
                                         spread(Species,Counts)

rownames(malt_genus.decontam_filtered_cmc) <- malt_genus.decontam_filtered_cmc$SampleID

malt_genus.decontam_filtered_cmc <- malt_genus.decontam_filtered_cmc %>% select(-SampleID)

malt_genus.decontam_filtered_cmc = malt_genus.decontam_filtered_cmc+1

```

```{r ancom_script, eval = F}
# source the ancom script to be able to use it here
source("./02-scripts.backup/ancom.R")

```

Update the metadata to include only the same samples as in the OTU table
```{r metadata_ancom}
metadata_new <- metadata %>%
  # filter(`Sample.ID` %in% outliers) %>% 
  filter(!str_detect(`Sample.ID`, outliersF)) %>%
  filter(!str_detect(`Sample.ID`, "EXB")) %>% 
  filter(!str_detect(`Sample.ID`, "LIB")) %>% 
  filter(!str_detect(`Sample.ID`, "10M"))

```


```{r input_tables_ancom}
# this works
# this converts the rownames to a column with the necessary heder for ANCOM, removes the rownames, then puts them back in from the column with the appropriate header
malt_species.decontam_filtered_noblanks_test <- malt_species.decontam_filtered_noblanks %>% rownames_to_column("Sample.ID") %>% remove_rownames() %>% column_to_rownames(var = "Sample.ID")

# sets the OTU.name variable as the column headers of the input matrix. Don't need this b/c it puts spaces back and won't run
OTU.name = colnames(malt_species.decontam_filtered_noblanks)

# something about setting the rowname variable to the appropriate format for ANCOM again
malt_species.decontam_filtered_noblanks_test <- data.frame(Sample.ID=rownames(malt_species.decontam_filtered_noblanks_test), as.matrix(malt_species.decontam_filtered_noblanks_test), row.names = NULL)

# # this puts back column names that got distorted by the step above, but they have spaces and won't run
# colnames(malt_species.decontam_filtered_noblanks_clr_test)=c("Sample.ID", OTU.name)

# # unnecessary, makes sure the data is a data.frame (but it already is)
# malt_species.decontam_filtered_noblanks_clr_test=as.data.frame(malt_species.decontam_filtered_noblanks_clr_test)



```

```{r input_tables_tidyverse}
# this should do the same as above but using fewer steps - except it keeps the spaces in names, which have to be removed
malt_species.decontam_filtered_noblanks_clr_test <- malt_species.decontam_filtered_noblanks_clr %>%
  rownames_to_column("Sample.ID") 


# trying to run this one in the next gives: Error in data.pair[, 1] : incorrect number of dimensions
malt_species.decontam_filtered_noblanks_test <- malt_species.decontam_filtered_noblanks %>%
  rownames_to_column("Sample.ID") %>%
  gather("Species", "Counts", 2:ncol(.)) %>%
  mutate(Species = str_replace_all(Species, " ", "_")) %>%
  mutate(Species = str_replace_all(Species, "\\.", "")) %>%
  mutate(Species = str_replace(Species, "\\[", "")) %>%
  mutate(Species = str_replace(Species, "\\]", "")) %>%
  spread(Species, Counts)


```


```{r run_ancom}
malt_species.decontam_filtered_noblanks.ancom <- ANCOM.main(OTUdat = malt_species.decontam_filtered_noblanks_test, Vardat = metadata_new, 
                                                                adjusted = F, repeated = F, main.var = "Village", adj.formula = NULL, repeat.var = "Village", 
                                                                longitudinal = T, random.formula = "~1|Village", multcorr=2, sig = 0.05, prev.cut = 0.90)


```



From Zandra's R notebook:
Prepare data:
```{r zandra_data_prep, eval = F}
metadata_z <- read_excel("~/Dropbox (MPI SHH)/1-Methods_Dental Arcade/3-Results/DA_metadata.xlsx")
colnames(metadata_z)[1] <- "Sample.ID"
metadata_z$Sample.ID <- gsub("01.SG1.1_S0_L001_R1_001.fastq.combined.fq.prefixed.extractunmapped.bam", "", metadata_z$Sample.ID)

otu_table <- read.delim("~/Dropbox (MPI SHH)/1-Methods_Dental Arcade/3-Results/MALT/malt_refseq_species_decontam_20191203.txt")
colnames(otu_table) <- gsub("01.SG1.1_S0_L001_R1_001.fastq.combined.fq.prefixed.extractunmapped.bam", "", colnames(otu_table))
# Transpose dataframe
otu_table_t <- otu_table %>%
   gather("Sample.ID", "count", 2:77) %>%
   spread(X.Datasets, count)

# I don't really know what this part is doing, but it's necessary to make the test work
otu_table_t <- otu_table_t %>% remove_rownames %>% column_to_rownames(var="Sample.ID")
OTU.name=colnames(otu_table_t)
otu_table_t=data.frame(Sample.ID=rownames(otu_table_t), 
                         as.matrix(otu_table_t), row.names = NULL)
# colnames(otu_table_t)=c("Sample.ID", OTU.name)
# otu_table_t=as.data.frame(otu_table_t)
```

Running ANCOM with a mixed effects model:
```{r zandra_run_ancom, eval = F}
# Note: this took about 10 minutes to run for species and 3 minutes for genus
res.W=ANCOM.main(OTUdat=otu_table_t, Vardat=metadata_z, adjusted=F, repeated=T,
                 main.var="Weight_class", adj.formula=NULL, repeat.var="Individual", longitudinal=T,
                 random.formula="~1|Individual", multcorr=2, sig=0.05, prev.cut=0.90)

res.ANCOM=res.W$W.taxa

write.table(res.ANCOM, "U:/Dental_arcade/ANCOM/ancom_species_weightclass_mixedeffects_BH_20200113.txt")
```


