---
title: "Cameroon hunter-gatherer calculus/plaque metadata stats"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
    github_document:
        fig_width: 8
        fig_height: 6
        toc: true
---

```{r load_libraries, echo = F, message = F}
library(knitr)
library(decontam)
library(data.table)
# library(psych)
library(vegan)
# library(ape)
library(mixOmics)
# library(compositions)
library(janitor)
# library(pander)
library(tidyverse)
library(gplots)
library(ggrepel)
library(viridis)
library(cowplot)
opts_chunk$set(echo=F, warning=F, message=F, dpi=150)
```

Set the working directory of the notebook to the parent directory of the 
notebook itself.  

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```


```{r load_data}

# load the taxonomy tables that have been decontaminated and the column headers are cleaned up
load("./05-results.backup/CMC_taxonomy_tables.RData")

# load the metadata file
load("./05-results.backup/CMC_metadata.RData")

# read in the mr1 species list
mr1_species <- fread("./05-results.backup/minres_oblimin_noblanks.fa_species.tsv") %>% select(Species) %>% pull()

metadata <- metadata %>%
  mutate(Individual_ID = str_trunc(SampleID, width = 6, side = "right", ellipsis = "")) %>%
  select(SampleID, Individual_ID, everything(.))


```


```{r pca_plotting_functions}
# plot PCA with colored dots and the title including the # of species or genera
plot_pca_titles <- function(df, pc1, pc2, color_group, shape_group, size_group, ncomps, title_text) {
    metadata_group_colors <- get(paste(color_group, "_colors", sep = ""))
    metadata_group_shapes <- get(paste(shape_group, "_shapes", sep = ""))
    metadata_group_size <- get(paste(size_group, "_size", sep = ""))

    pca.list <- mixOmics::pca(df, ncomp = ncomps, logratio = 'CLR')

    exp_var <- paste0(round(pca.list$explained_variance * 100, 2), "%")
    df_X <- pca.list$variates$X %>%
              as.data.frame() %>%
              rownames_to_column("SampleID") %>%
              inner_join(metadata %>%
                           select(SampleID, Env, Description, Ethnic_Group, Age_group, Sex, Market_economy, Village, Tooth_site, 
                                  Type, Decayed, Missing, Moving, Altered, Root_visible, Bleeding), by = "SampleID") %>%
      mutate(Decayed = ifelse(is.na(Decayed), "No", "Yes"),
             Missing = ifelse(is.na(Missing), "No","Yes"),
             Root_visible = ifelse(is.na(Root_visible), "No","Yes"),
             Altered = ifelse(is.na(Altered), "No","Yes"))

    color_group = df_X[[color_group]]
    shape_group = df_X[[shape_group]]
    size_group = df_X[[size_group]]
   
                       if (pc1 == 'PC1') {
                           pc1 <- df_X$PC1
                           exp_var_pc1 <- exp_var[1]
                           xaxis <- c("PC1")
                       }  else if (pc1 == 'PC2') {
                           pc1 <- df_X$PC2
                           exp_var_pc1 <- exp_var[2]
                           xaxis <- c("PC2")
                       } else if (pc1 == 'PC3') {
                           pc1 <- df_X$PC3
                           exp_var_pc1 <- exp_var[3]
                           xaxis <- c("PC3")
                       }

                       if (pc2 == 'PC1') {
                           pc2 <- df_X$PC1
                           exp_var_pc2 <- exp_var[1]
                           yaxis <- c("PC1")
                       }  else if (pc2 == 'PC2') {
                           pc2 <- df_X$PC2
                           exp_var_pc2 <- exp_var[2]
                           yaxis <- c("PC2")
                       } else if (pc2 == 'PC3') {
                           pc2 <- df_X$PC3
                           exp_var_pc2 <- exp_var[3]
                           yaxis <- c("PC3")
                       }

    pca_plot <- ggplot(df_X, aes(pc1, pc2, colour = color_group, shape = shape_group, size = size_group)) +
                        geom_point() +
                        scale_colour_manual(values = metadata_group_colors) +
                        scale_shape_manual(values = metadata_group_shapes) +
                        scale_size_manual(values = metadata_group_size) +
                        # stat_ellipse() +
                        xlab(paste(xaxis, " - ", exp_var_pc1)) +
                        ylab(paste(yaxis, " - ", exp_var_pc2)) +
                        theme_minimal(base_size = 10) +
                        theme(legend.position = "top") +
                        ggtitle(paste(title_text))

    return(pca_plot)
}

```

```{r graphing_functions}

# plotting box and whisker
plot_box_whisker <- function(df, hasmtdta = c("TRUE","FALSE"), stat_info, metadata_group, fill_group, title_text) {
    fill_group_colors <- get(paste(fill_group, "_colors", sep = ""))

    if (hasmtdta == T) { 
      df_X <- df
      fill_group = df_X[[fill_group]]
    } else {
      df_X <- df %>%
              inner_join(metadata %>%
                           select(SampleID, Env, Description, Ethnic_Group, Age_group,
                                  Sex, Market_economy, Village, Tooth_site, Type), by = "SampleID")
      fill_group = df_X[[metadata_group]]
    }
   
    stat_info_table = df_X[[stat_info]]
    metadata_group = df_X[[metadata_group]]

    bx_wh_plot <- ggplot(df_X, aes(x = metadata_group, y = stat_info_table, fill = fill_group)) +
                         geom_boxplot() +
                         scale_fill_manual(values = fill_group_colors) +
                         theme_minimal() +
                         #scale_y_continuous(trans='log10') +
                         #scale_y_continuous(trans='pseudo_log') +
                         theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
                         ylab(stat_info) +
                         ggtitle(title_text)

    return(bx_wh_plot)
}

```

```{r outliers}
outliers <- c("CMC002.B0201","CMC032.B0101","CMC037.B0201","CMC047.A0201",
              "EXB059.A1901","EXB059.A1301","EXB059.A1101","EXB059.A0901",
              "SRR1646041","SRR1646032","SRR1646042","SRR1646045","SRR1646030","SRR1646047")

outliersF <- str_c(outliers, collapse = "|")


```

```{r pca_plots}


malt_species.decontam_filtered <- malt_species.decontam %>%
  select(matches("CMC|Species")) %>%
  select(-one_of(outliers)) %>%
  adorn_totals(where = "col", name = "Sum_species.decontam_filtered") %>%
  filter(Species %in% mr1_species) %>%
  gather("SampleID","Counts",2:ncol(.)) %>%
  mutate(Counts = Counts + 1) %>%
  spread(Species,Counts) %>%
  column_to_rownames("SampleID")

# prepare to run a PCA
# check the number of components to retain by tuning the PCA
tune.pca(malt_species.decontam_filtered, logratio = 'CLR')

# Define new colors
Decayed_colors = c("#065FA3","#FF3200")
Decayed_shapes = c(17,19)
Decayed_size = c(4,4)

Missing_colors = c("#065FA3","#FF3200")
Missing_shapes = c(17,19)
Missing_size = c(4,4)

Root_visible_colors = c("#065FA3","#FF3200")
Root_visible_shapes = c(17,19)
Root_visible_size = c(4,4)

Altered_colors = c("#065FA3","#FF3200")
Altered_shapes = c(17,19)
Altered_size = c(4,4)

# perform and plot a PCA to see how the data cluster
plot_pca_titles(malt_species.decontam_filtered, "PC1", "PC2", "Decayed", "Tooth_site", "Decayed", 3, "Decayed teeth, PC1-PC2")
plot_pca_titles(malt_species.decontam_filtered, "PC3", "PC2", "Decayed", "Tooth_site", "Decayed", 3, "Decayed teeth, PC3-PC2")

plot_pca_titles(malt_species.decontam_filtered, "PC1", "PC2", "Missing", "Tooth_site", "Missing", 3, "Missing teeth, PC1-PC2")
plot_pca_titles(malt_species.decontam_filtered, "PC3", "PC2", "Missing", "Tooth_site", "Missing", 3, "Missing teeth, PC3-PC2")

plot_pca_titles(malt_species.decontam_filtered, "PC1", "PC2", "Root_visible", "Tooth_site", "Root_visible", 3, "Root visible teeth, PC1-PC2")
plot_pca_titles(malt_species.decontam_filtered, "PC3", "PC2", "Root_visible", "Tooth_site", "Root_visible", 3, "Root visible teeth, PC3-PC2")

plot_pca_titles(malt_species.decontam_filtered, "PC1", "PC2", "Altered", "Tooth_site", "Altered", 3, "Altered teeth, PC1-PC2")
plot_pca_titles(malt_species.decontam_filtered, "PC3", "PC2", "Altered", "Tooth_site", "Altered", 3, "Altered teeth, PC3-PC2")


```

```{r differences}
# number of anterior/posterior samples
plot <- metadata %>%
  filter(str_detect(Ethnic_Group, "Baka|Nzime")) %>%
  group_by(Ethnic_Group, Tooth_site) %>%
  count() %>%
  ggplot(., aes(x = Ethnic_Group, y = n, fill = Tooth_site)) +
         geom_bar(stat = "identity", position = "dodge", color = "black") +
         scale_fill_manual(values = Tooth_site_colors) +
         theme_minimal(base_size = 14) +
         theme(axis.text.x = element_text(hjust = 0.5),
               axis.text = element_text(size = 14)) +
         ylab(" # Samples from anterior/posterior sites") +
         ggtitle("Tooth site")
plot
ggsave("./06-publication/supplemental_figures/SXX42/panel_parts/SXX42_eg_ts_plot.pdf", plot = plot, device = "pdf",
       scale = 1, width = 7, height = 5, units = c("in"), dpi = 300)

# number of paired samples
plot <- metadata %>%
  filter(str_detect(Ethnic_Group, "Baka|Nzime")) %>%
  count(Individual_ID, name = "Counts") %>%
  filter(Counts > 1) %>%
  inner_join(., metadata %>% select(Individual_ID, Ethnic_Group, Tooth_site)) %>%
  group_by(Ethnic_Group, Tooth_site) %>%
  count() %>%
  ggplot(., aes(x = Ethnic_Group, y = n, fill = Tooth_site)) +
         geom_bar(stat = "identity", position = "dodge", color = "black") +
         scale_fill_manual(values = Tooth_site_colors) +
         theme_minimal(base_size = 14) +
         theme(axis.text.x = element_text(hjust = 0.5),
               axis.text = element_text(size = 14)) +
         ylab(" # paired samples") +
         ggtitle("Paired tooth site samples")
plot
ggsave("./06-publication/supplemental_figures/SXX42/panel_parts/SXX42_eg_ts_paired_plot.pdf", plot = plot, device = "pdf",
       scale = 1, width = 7, height = 5, units = c("in"), dpi = 300)


# Decayed teeth
plot <- metadata %>%
  filter(str_detect(Ethnic_Group, "Baka|Nzime")) %>%
  mutate(Decayed = ifelse(is.na(Decayed), "No", "Yes"),
         Counts = 1) %>%
  group_by(Ethnic_Group, Decayed) %>%
  count() %>%
  ggplot(., aes(x = Ethnic_Group, y = n, fill = Decayed)) +
         geom_bar(stat = "identity", position = "dodge", color = "black") +
         scale_fill_manual(values = Decayed_colors) +
         theme_minimal(base_size = 14) +
         theme(axis.text.x = element_text(hjust = 0.5),
               axis.text = element_text(size = 14)) +
         ylab(" # Samples with decayed teeth") +
         ggtitle("Decayed")
plot
ggsave("./06-publication/supplemental_figures/SXX42/panel_parts/SXX42_eg_decayed_plot.pdf", plot = plot, device = "pdf",
       scale = 1, width = 7, height = 5, units = c("in"), dpi = 300)

# Missing teeth
plot <- metadata %>%
  filter(str_detect(Ethnic_Group, "Baka|Nzime")) %>%
  mutate(Missing = ifelse(is.na(Missing), "No", "Yes"),
         Counts = 1) %>%
  group_by(Ethnic_Group, Missing) %>%
  count() %>%
  ggplot(., aes(x = Ethnic_Group, y = n, fill = Missing)) +
         geom_bar(stat = "identity", position = "dodge", color = "black") +
         scale_fill_manual(values = Missing_colors) +
         theme_minimal(base_size = 14) +
         theme(axis.text.x = element_text(hjust = 0.5),
               axis.text = element_text(size = 14)) +
         ylab(" # Samples with missing teeth") +
         ggtitle("Missing")
plot
ggsave("./06-publication/supplemental_figures/SXX42/panel_parts/SXX42_eg_missing_plot.pdf", plot = plot, device = "pdf",
       scale = 1, width = 7, height = 5, units = c("in"), dpi = 300)

# Teeth with root visible
plot <- metadata %>%
  filter(str_detect(Ethnic_Group, "Baka|Nzime")) %>%
  mutate(Root_visible = ifelse(is.na(Root_visible), "No", "Yes"),
         Counts = 1) %>%
  group_by(Ethnic_Group, Root_visible) %>%
  count() %>%
  ggplot(., aes(x = Ethnic_Group, y = n, fill = Root_visible)) +
         geom_bar(stat = "identity", position = "dodge", color = "black") +
         scale_fill_manual(values = Root_visible_colors) +
         theme_minimal(base_size = 14) +
         theme(axis.text.x = element_text(hjust = 0.5),
               axis.text = element_text(size = 14)) +
         ylab(" # Samples with root visible teeth") +
         ggtitle("Root visible")
plot
ggsave("./06-publication/supplemental_figures/SXX42/panel_parts/SXX42_eg_rv_plot.pdf", plot = plot, device = "pdf",
       scale = 1, width = 7, height = 5, units = c("in"), dpi = 300)

# Altered teeth
plot <- metadata %>%
  filter(str_detect(Ethnic_Group, "Baka|Nzime")) %>%
  mutate(Altered = ifelse(is.na(Altered), "No", "Yes"),
         Counts = 1) %>%
  group_by(Ethnic_Group, Altered) %>%
  count() %>%
  ggplot(., aes(x = Ethnic_Group, y = n, fill = Altered)) +
         geom_bar(stat = "identity", position = position_dodge2(width = 0.9, preserve = "single"), color = "black") +
         scale_fill_manual(values = Altered_colors) +
         theme_minimal(base_size = 14) +
         theme(axis.text.x = element_text(hjust = 0.5),
               axis.text = element_text(size = 14)) +
         ylab(" # Samples with altered teeth") +
         ggtitle("Altered")
plot
ggsave("./06-publication/supplemental_figures/SXX42/panel_parts/SXX42_eg_altered_plot.pdf", plot = plot, device = "pdf",
       scale = 1, width = 7, height = 5, units = c("in"), dpi = 300)


```

```{r}

# Decayed teeth
plot <- metadata %>%
  filter(str_detect(Ethnic_Group, "Baka|Nzime")) %>%
  mutate(Decayed = ifelse(is.na(Decayed), "No", "Yes"),
         Counts = 1) %>%
  group_by(Ethnic_Group, Age_group, Decayed) %>%
  count() %>%
  ggplot(., aes(x = Age_group, y = n, fill = Decayed)) +
         geom_bar(stat = "identity", position = position_dodge2(width = 0.9, preserve = "single"), color = "black") +
         scale_fill_manual(values = Decayed_colors) +
         theme_minimal(base_size = 14) +
         theme(axis.text.x = element_text(hjust = 0.5, size = 12),
               axis.text.y = element_text(size = 14)) +
         ylab(" # Samples") +
         ggtitle("Decayed") +
  facet_wrap(~Ethnic_Group)
plot
ggsave("./06-publication/supplemental_figures/SXX42/panel_parts/SXX42_decayed_age_plot.pdf", plot = plot, device = "pdf",
       scale = 1, width = 7, height = 5, units = c("in"), dpi = 300)

# Missing teeth
plot <- metadata %>%
  filter(str_detect(Ethnic_Group, "Baka|Nzime")) %>%
  mutate(Missing = ifelse(is.na(Missing), "No", "Yes"),
         Counts = 1) %>%
  group_by(Ethnic_Group, Age_group, Missing) %>%
  count() %>%
  ggplot(., aes(x = Age_group, y = n, fill = Missing)) +
         geom_bar(stat = "identity", position = position_dodge2(width = 0.9, preserve = "single"), color = "black") +
         scale_fill_manual(values = Missing_colors) +
         theme_minimal(base_size = 14) +
         theme(axis.text.x = element_text(hjust = 0.5, size = 12),
               axis.text.y = element_text(size = 14)) +
         ylab(" # Samples") +
         ggtitle("Missing") +
  facet_wrap(~Ethnic_Group)
plot
ggsave("./06-publication/supplemental_figures/SXX42/panel_parts/SXX42_missing_age_plot.pdf", plot = plot, device = "pdf",
       scale = 1, width = 7, height = 5, units = c("in"), dpi = 300)

# Root visible teeth
plot <- metadata %>%
  filter(str_detect(Ethnic_Group, "Baka|Nzime")) %>%
  mutate(Root_visible = ifelse(is.na(Root_visible), "No", "Yes"),
         Counts = 1) %>%
  group_by(Ethnic_Group, Age_group, Root_visible) %>%
  count() %>%
  ggplot(., aes(x = Age_group, y = n, fill = Root_visible)) +
         geom_bar(stat = "identity", position = position_dodge2(width = 0.9, preserve = "single"), color = "black") +
         scale_fill_manual(values = Root_visible_colors) +
         theme_minimal(base_size = 14) +
         theme(axis.text.x = element_text(hjust = 0.5, size = 12),
               axis.text.y = element_text(size = 14)) +
         ylab(" # Samples") +
         ggtitle("Root visible") +
  facet_wrap(~Ethnic_Group)
plot
ggsave("./06-publication/supplemental_figures/SXX42/panel_parts/SXX42_rv_age_plot.pdf", plot = plot, device = "pdf",
       scale = 1, width = 7, height = 5, units = c("in"), dpi = 300)

# Altered teeth
plot <- metadata %>%
  filter(str_detect(Ethnic_Group, "Baka")) %>%
  mutate(Altered = ifelse(is.na(Altered), "No", "Yes"),
         Root_visible = ifelse(is.na(Root_visible), "No", "Yes"),
         Counts = 1) %>%
  group_by(Ethnic_Group, Root_visible, Altered) %>%
  count() %>%
  ggplot(., aes(x = Altered, y = n, fill = Root_visible)) +
         geom_bar(stat = "identity", position = position_dodge2(width = 0.9, preserve = "single"), color = "black") +
         scale_fill_manual(values = Root_visible_colors) +
         theme_minimal(base_size = 14) +
         theme(axis.text.x = element_text(hjust = 0.5),
               axis.text = element_text(size = 14)) +
         ylab(" # Samples") +
         ggtitle("Altered - Root visible") +
  facet_wrap(~Ethnic_Group)
plot
ggsave("./06-publication/supplemental_figures/SXX42/panel_parts/SXX42_altered_rv_plot.pdf", plot = plot, device = "pdf",
       scale = 1, width = 7, height = 5, units = c("in"), dpi = 300)

# Altered teeth
plot <- metadata %>%
  filter(str_detect(Ethnic_Group, "Baka")) %>%
  mutate(Altered = ifelse(is.na(Altered), "No", "Yes"),
         Root_visible = ifelse(is.na(Root_visible), "No", "Yes"),
         Counts = 1) %>%
  group_by(Ethnic_Group, Age_group, Altered) %>%
  count() %>%
  ggplot(., aes(x = Age_group, y = n, fill = Altered)) +
         geom_bar(stat = "identity", position = position_dodge2(width = 0.9, preserve = "single"), color = "black") +
         scale_fill_manual(values = Root_visible_colors) +
         theme_minimal(base_size = 14) +
         theme(axis.text.x = element_text(hjust = 0.5),
               axis.text = element_text(size = 14)) +
         ylab(" # Samples") +
         ggtitle("Altered - Age group") +
  facet_wrap(~Ethnic_Group)
plot
ggsave("./06-publication/supplemental_figures/SXX42/panel_parts/SXX42_altered_age_plot.pdf", plot = plot, device = "pdf",
       scale = 1, width = 7, height = 5, units = c("in"), dpi = 300)


```

```{r}

# Decayed teeth
plot <- metadata %>%
  filter(str_detect(Ethnic_Group, "Baka|Nzime")) %>%
  mutate(Decayed = ifelse(is.na(Decayed), "No", "Yes"),
         Counts = 1) %>%
  group_by(Village, Decayed) %>%
  count() %>%
  ggplot(., aes(x = Village, y = n, fill = Decayed)) +
         geom_bar(stat = "identity", position = "dodge", color = "black") +
         scale_fill_manual(values = Decayed_colors) +
         theme_minimal(base_size = 14) +
         theme(axis.text.x = element_text(hjust = 0.5),
               axis.text = element_text(size = 14)) +
         ylab(" # Samples") +
         ggtitle("Decayed") 
plot
ggsave("./06-publication/supplemental_figures/SXX42/panel_parts/SXX42_decayed_village_plot.pdf", plot = plot, device = "pdf",
       scale = 1, width = 7, height = 5, units = c("in"), dpi = 300)

# Missing teeth
plot <- metadata %>%
  filter(str_detect(Ethnic_Group, "Baka|Nzime")) %>%
  mutate(Missing = ifelse(is.na(Missing), "No", "Yes"),
         Counts = 1) %>%
  group_by(Village, Missing) %>%
  count() %>%
  ggplot(., aes(x = Village, y = n, fill = Missing)) +
         geom_bar(stat = "identity", position = "dodge", color = "black") +
         scale_fill_manual(values = Missing_colors) +
         theme_minimal(base_size = 14) +
         theme(axis.text.x = element_text(hjust = 0.5),
               axis.text = element_text(size = 14)) +
         ylab(" # Samples") +
         ggtitle("Missing")
plot
ggsave("./06-publication/supplemental_figures/SXX42/panel_parts/SXX42_missing_village_plot.pdf", plot = plot, device = "pdf",
       scale = 1, width = 7, height = 5, units = c("in"), dpi = 300)


```


```{r}
# Decayed teeth
plot <- metadata %>%
  filter(str_detect(Ethnic_Group, "Baka|Nzime")) %>%
  mutate(Decayed = ifelse(is.na(Decayed), "No", "Yes"),
         Counts = 1) %>%
  group_by(Ethnic_Group, Market_economy, Decayed) %>%
  count() %>%
  ggplot(., aes(x = Market_economy, y = n, fill = Decayed)) +
         geom_bar(stat = "identity", position = "dodge", color = "black") +
         scale_fill_manual(values = Decayed_colors) +
         theme_minimal(base_size = 14) +
         theme(axis.text.x = element_text(hjust = 0.5)) +
         ylab(" # Samples") +
         ggtitle("Decayed")
plot
ggsave("./06-publication/supplemental_figures/SXX42/panel_parts/SXX42_decayed_market_plot.pdf", plot = plot, device = "pdf",
       scale = 1, width = 7, height = 5, units = c("in"), dpi = 300)

# Missing teeth
plot <- metadata %>%
  filter(str_detect(Ethnic_Group, "Baka|Nzime")) %>%
  mutate(Missing = ifelse(is.na(Missing), "No", "Yes"),
         Counts = 1) %>%
  group_by(Ethnic_Group, Market_economy, Missing) %>%
  count() %>%
  ggplot(., aes(x = Market_economy, y = n, fill = Missing)) +
         geom_bar(stat = "identity", position = "dodge", color = "black") +
         scale_fill_manual(values = Missing_colors) +
         theme_minimal(base_size = 14) +
         theme(axis.text.x = element_text(hjust = 0.5)) +
         ylab(" # Samples") +
         ggtitle("Missing")
plot
ggsave("./06-publication/supplemental_figures/SXX42/panel_parts/SXX42_missing_market_plot.pdf", plot = plot, device = "pdf",
       scale = 1, width = 7, height = 5, units = c("in"), dpi = 300)

# Root visible teeth
 plot <- metadata %>%
  filter(str_detect(Ethnic_Group, "Baka|Nzime")) %>%
  mutate(Root_visible = ifelse(is.na(Root_visible), "No", "Yes"),
         Counts = 1) %>%
  group_by(Ethnic_Group, Market_economy, Root_visible) %>%
  count() %>%
  ggplot(., aes(x = Market_economy, y = n, fill = Root_visible)) +
         geom_bar(stat = "identity", position = "dodge", color = "black") +
         scale_fill_manual(values = Root_visible_colors) +
         theme_minimal(base_size = 14) +
         theme(axis.text.x = element_text(hjust = 0.5)) +
         ylab(" # Samples") +
         ggtitle("Root visible")
plot
ggsave("./06-publication/supplemental_figures/SXX42/panel_parts/SXX42_rv_market_plot.pdf", plot = plot, device = "pdf",
       scale = 1, width = 7, height = 5, units = c("in"), dpi = 300)

```

```{r}

```


```{r alpha_div}

# make Relab binary to make a presence/absence table
presabs_table <- malt_species.decontam %>%
  select(-one_of(outliers)) %>%
  select(-matches("EXB|LIB|JAE|SRR")) %>%
  adorn_totals(where = "col", name = "Sum_species.decontam") %>%
  mutate(Percent = Sum_species.decontam/sum(Sum_species.decontam)*100) %>%
  select(-one_of(c("Sum_species.decontam","Percent"))) %>%
  gather("SampleID","Counts",2:ncol(.)) %>%
  spread(Species,Counts) %>%
  gather("Species","Counts",2:ncol(.)) %>%
  mutate(Counts = ifelse(Counts > 0, 1, 0)) %>%
  spread(Species, Counts) %>%
  column_to_rownames("SampleID")

# calculate observed species for each sample with janitor 'adorn_totals'
malt_species.decontam.alpha <- presabs_table %>%
  adorn_totals(., where = "col", name = "Observed_species") %>%
  select(Observed_species) %>%
  rownames_to_column("SampleID") 

# shannon index
malt_species.decontam.matrix <- as.matrix(malt_species.decontam %>%
  select(-one_of(outliers)) %>%
  select(-matches("EXB|LIB|JAE|SRR")) %>%
  adorn_totals(where = "col", name = "Sum_species.decontam") %>%
  mutate(Percent = Sum_species.decontam/sum(Sum_species.decontam)*100) %>%
  select(-one_of(c("Sum_species.decontam","Percent"))) %>%
  gather("SampleID","Counts",2:ncol(.)) %>%
  spread(Species,Counts) %>% 
  column_to_rownames("SampleID"))
 
malt_species.decontam.shannon <- as.data.frame(diversity(malt_species.decontam.matrix, index = "shannon"))
names(malt_species.decontam.shannon)[1] <- "Shannon_index"

# merge with the metadata file and plot
malt_species.decontam.alpha <- malt_species.decontam.os %>%
  full_join(., malt_species.decontam.shannon %>%
  rownames_to_column("SampleID")) %>%
  inner_join(metadata %>%
              # filter(str_detect(SampleID, "Baka|Nzime")) %>%
              select(SampleID, Decayed, Altered, Missing, Root_visible, Ethnic_Group, Age_group,
                      Sex, Market_economy, Village, Tooth_site, Type), by = "SampleID") %>%
  mutate(Altered = ifelse(is.na(Altered), "No", "Yes"),
         Decayed = ifelse(is.na(Decayed), "No", "Yes"),
         Missing = ifelse(is.na(Missing), "No", "Yes"),
         Root_visible = ifelse(is.na(Root_visible), "No", "Yes"))


# plot
os_plot <-malt_species.decontam.alpha %>%
  ggplot(., aes(x = Ethnic_Group, y = Observed_species, fill = Decayed)) +
          geom_boxplot() +
          scale_fill_manual(values = Decayed_colors) +
          theme_minimal(base_size = 18) +
          theme(axis.text.x = element_text(angle = 0, hjust = 0.5),
                text = element_text(size=18)) +
          ylab("Number of Species") +
          xlab("")
os_plot

shannon_plot <-malt_species.decontam.alpha %>%
  ggplot(., aes(x = Ethnic_Group, y = Shannon_index, fill = Decayed)) +
          geom_boxplot() +
          scale_fill_manual(values = Decayed_colors) +
          theme_minimal(base_size = 18) +
          theme(axis.text.x = element_text(angle = 0, hjust = 0.5),
                text = element_text(size=18)) +
          ylab("Shannon index") +
          xlab("")
shannon_plot

# ggsave("./06-publication/supplemental_figures/SXX5/SXX5_os.pdf", plot = os_plot, device = "pdf",
#        scale = 1, width = 7, height = 5, units = c("in"), dpi = 300)

# now on filtered tables
presabs_table_f <- malt_species.decontam %>%
  select(-one_of(outliers)) %>%
  select(-matches("EXB|LIB|JAE|SRR")) %>%
  adorn_totals(where = "col", name = "Sum_species.decontam") %>%
  mutate(Percent = Sum_species.decontam/sum(Sum_species.decontam)*100) %>%
  filter(Percent > 0.001) %>%
  select(-one_of(c("Sum_species.decontam","Percent"))) %>%
  gather("SampleID","Counts",2:ncol(.)) %>%
  spread(Species,Counts) %>%
  gather("Species","Counts",2:ncol(.)) %>%
  mutate(Counts = ifelse(Counts > 0, 1, 0)) %>%
  spread(Species, Counts) %>%
  column_to_rownames("SampleID")
  
# calculate observed species for each sample with janitor 'adorn_totals'
malt_species.decontam_filtered.alpha <- presabs_table_f %>%
  adorn_totals(., where = "col", name = "Observed_species") %>%
  select(Observed_species) %>%
  rownames_to_column("SampleID") 

# shannon index
malt_species.decontam_filter.matrix <- as.matrix(malt_species.decontam %>%
  select(-one_of(outliers)) %>%
  select(-matches("EXB|LIB|JAE|SRR")) %>%
  adorn_totals(where = "col", name = "Sum_species.decontam") %>%
  mutate(Percent = Sum_species.decontam/sum(Sum_species.decontam)*100) %>%
  filter(Percent > 0.001) %>%
  select(-one_of(c("Sum_species.decontam","Percent"))) %>%
  gather("SampleID","Counts",2:ncol(.)) %>%
  spread(Species,Counts) %>% 
  column_to_rownames("SampleID"))
 
malt_species.decontam_filter.shannon <- as.data.frame(diversity(malt_species.decontam_filter.matrix, index = "shannon"))
names(malt_species.decontam_filter.shannon)[1] <- "Shannon_index"

# merge with the metadata file and plot
malt_species.decontam_filtered.alpha <- malt_species.decontam_filtered.alpha %>%
  full_join(., malt_species.decontam_filter.shannon %>%
  rownames_to_column("SampleID")) %>%
  inner_join(metadata %>%
              # filter(str_detect(SampleID, "Baka|Nzime")) %>%
              select(SampleID, Decayed, Altered, Missing, Root_visible, Ethnic_Group, Age_group,
                      Sex, Market_economy, Village, Tooth_site, Type), by = "SampleID") %>%
  mutate(Altered = ifelse(is.na(Altered), "No", "Yes"),
         Decayed = ifelse(is.na(Decayed), "No", "Yes"),
         Missing = ifelse(is.na(Missing), "No", "Yes"),
         Root_visible = ifelse(is.na(Root_visible), "No", "Yes"))


# plot
malt_species.decontam_filtered.alpha %>%
  ggplot(., aes(x = Ethnic_Group, y = Observed_species, fill = Decayed)) +
          geom_boxplot() +
          scale_fill_manual(values = Decayed_colors) +
          theme_minimal(base_size = 18) +
          theme(axis.text.x = element_text(angle = 0, hjust = 0.5),
               text = element_text(size=18)) +
          ylab("Number of Species") +
          xlab("")


malt_species.decontam_filtered.alpha %>%
  ggplot(., aes(x = Ethnic_Group, y = Shannon_index, fill = Decayed)) +
          geom_boxplot() +
          scale_fill_manual(values = Decayed_colors) +
          theme_minimal(base_size = 18) +
          theme(axis.text.x = element_text(angle = 0, hjust = 0.5),
                text = element_text(size=18)) +
          ylab("Shannon index") +
          xlab("")


```

```{r}


```


```{r}
# number of paired samples
metadata %>%
  filter(str_detect(Ethnic_Group, "Baka|Nzime")) %>%
  count(Individual_ID, name = "Counts") %>%
  filter(Counts > 1) %>%
  inner_join(., metadata %>% select(Individual_ID, Ethnic_Group, Tooth_site)) %>%
  unique() %>%
  group_by(Ethnic_Group, Tooth_site) %>%
  count(Ethnic_Group) %>%
  ggplot(., aes(x = Ethnic_Group, y = n, fill = Tooth_site)) +
         geom_bar(stat = "identity", position = "dodge") +
         scale_fill_manual(values = Tooth_site_colors) +
         theme_minimal(base_size = 14) +
         theme(axis.text.x = element_text(hjust = 0.5)) +
         ylab(" # Samples from anterior/posterior sites") +
         ggtitle("Tooth site")

```































