---
title: "Bacteriodetes/Firmicutes Bacteriodes/Prevotella Main Figure"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
    github_document:
        fig_width: 8
        fig_height: 6
        toc: true
---

```{r load_libraries, echo = F, message = F}
library(knitr)
library(data.table)
library(janitor)
library(vegan)
library(compositions)
library(tidyverse)
library(gplots)
library(ggrepel)
library(viridis)
library(patchwork)
opts_chunk$set(echo=F, warning=F, message=F, dpi=150)
```

Set the working directory of the notebook to the parent directory of the 
notebook itself.  

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("../../.."))
```

```{r}
# load the metadata file
load("./05-results.backup/CMC_metadata.RData")

```


Load data files 
```{r load_hm_data}
# load the taxonomy tables that have been decontaminated and the column headers are cleaned up
load("./05-results.backup/CMC_taxonomy_tables.RData")

# load the metadata file
load("./05-results.backup/CMC_metadata.RData")

Village_colors <- c(`202` = "#FF3200", `205` = "#EF8158", `204` = "#E9BD8E", `203` = "#CBDDA7", `206` = "#38BCAD", `Industrial plaque` = "#969696", `Industrial calculus` = "#feb24c", ExtractionGauze = "#252525", ExtractionBlank = "#737373", LibraryBlank = "#bdbdbd")

metadata <- metadata %>%
  mutate(Market_integration_split = fct_relevel(Market_integration_split, "Logging road","Forest camp", "Farming","Industrial plaque","Industrial calculus"))

# load the metadata file again without factors for stats
metadata_nofactors <- fread("./00-documentation.backup/01-cameroon_hunter_gatherer_metadata.tsv")
metadata_nofactors <- metadata_nofactors %>% 
  rename(SampleID = `#SampleID`) %>%
  select(SampleID, Env, Age, Age_group, Ethnic_Group, Market_integration, Market_integration_split, Sex, Tooth_site, Village, Is_Oral)

```

```{r outliers}
outliers <- c("CMC002.B0201","CMC032.B0101","CMC037.B0201","CMC047.A0201",
              "EXB059.A1901","EXB059.A1301","EXB059.A1101","EXB059.A0901",
              "SRR1646041","SRR1646032","SRR1646042","SRR1646045","SRR1646030","SRR1646047")

```


```{r phylum_table}
phylum <- fread("./05-results.backup/MALT_all_data_combined_phylum.tsv") %>%
  rename(Phylum = 1) %>%
  select(-matches("VLC")) %>%
  full_join(., fread("./05-results.backup/Iberian_samples-controls_phylum.tsv") %>%
              rename(Phylum = 1) %>%
              select(matches("Phylum|VLC|SRR")), by = "Phylum") %>%
  pivot_longer(!Phylum, names_to = "SampleID", values_to = "Counts") %>%
  mutate(SampleID = str_replace_all(SampleID, ".SG1.unmapped",""),
         SampleID = str_replace_all(SampleID, ".unmapped",""))  %>%
  pivot_wider(names_from = "SampleID", values_from = "Counts")


```

# 50 most-abundant taxa
```{r metadata_heatmaps}
# read in metadata again to get it without all the factors
metadata_hm <- fread("./00-documentation.backup/01-cameroon_hunter_gatherer_metadata.tsv")

# order the samples so they can be ordered this way in the heat maps

# order the CMC samples by Village
cmc_order <- metadata_hm %>%
  rename(SampleID = `#SampleID`)  %>%
  as_tibble() %>%
  filter(str_detect(SampleID, "CMC")) %>%
  mutate(Village = fct_relevel(Village, "202","205","204","203","206")) %>%
  select(SampleID, Village) %>%
  arrange(Village) %>%
  pull(SampleID)

# order the HMP samples by subplaque, supraplaque
hmp_order <- metadata_hm %>%
  rename(SampleID = `#SampleID`)  %>%
  as_tibble() %>%
  filter(str_detect(SampleID, "SRR")) %>%
  filter(!str_detect(SampleID, "10M|SRR164")) %>%
  mutate(Description = fct_relevel(Description, "HMP_subPlaque","HMP_supPlaque")) %>%
  select(SampleID, Description) %>%
  arrange(Description) %>%
  pull(SampleID)

# keep JAE samples in alphabetical order
jae_order <- metadata_hm %>%
  rename(SampleID = `#SampleID`)  %>%
  as_tibble() %>%
  filter(str_detect(SampleID, "JAE|VLC")) %>%
  filter(!str_detect(SampleID, "10M")) %>%
  pull(SampleID)

# combine all 3 ordered vectors into a final ordered vector
each_order <- c(cmc_order, hmp_order, jae_order)

```


```{r heatmaps_species_each}
# select the top 50 most abundant species for CMC samples
malt_species.decontam_top50_cmc <- malt_species.decontam %>%
  select(-one_of(outliers)) %>%
  select(matches("Species|CMC")) %>%
  adorn_totals(where = "col", name = "Sum_species.decontam") %>%
  mutate(Percent = Sum_species.decontam/sum(Sum_species.decontam)*100) %>%
  top_n(50, Percent) %>%
  select(-one_of("Sum_species.decontam","Percent")) %>%
  gather("SampleID","Counts",2:ncol(.)) %>%
  mutate(Counts = Counts + 1) %>%
  spread(Species,Counts) %>%
  column_to_rownames("SampleID")

# also save the species as a vector
malt_species.decontam_top50_cmcV <- malt_species.decontam %>%
  select(-one_of(outliers)) %>%
  select(matches("Species|CMC")) %>%
  adorn_totals(where = "col", name = "Sum_species.decontam") %>%
  mutate(Percent = Sum_species.decontam/sum(Sum_species.decontam)*100) %>%
  top_n(50, Percent) %>%
  select(-one_of("Sum_species.decontam","Percent")) %>%
  gather("SampleID","Counts",2:ncol(.)) %>%
  spread(SampleID,Counts) %>%
  select(Species) %>%
  mutate(CMC = 1)

# select the top 50 most abundant species for HMP samples
nothmp <- metadata_nofactors %>%
  filter(!str_detect(Is_Oral, "HMP")) %>%
  select(SampleID) %>%
  pull()

malt_species.decontam_top50_hmpV <- malt_species.decontam %>%
  select(-one_of(outliers)) %>%
  select(-matches(nothmp)) %>%
  adorn_totals(where = "col", name = "Sum_species.decontam") %>%
  mutate(Percent = Sum_species.decontam/sum(Sum_species.decontam)*100) %>%
  top_n(50, Percent) %>%
  select(-one_of("Sum_species.decontam","Percent")) %>%
  gather("SampleID","Counts",2:ncol(.)) %>%
  spread(SampleID,Counts) %>%
  select(Species) %>%
  mutate(HMP = 1)

# select the top 50 most abundant species for JAE samples
malt_species.decontam_top50_jaeV <- malt_species.decontam %>%
  select(-one_of(outliers)) %>%
  select(matches("Species|JAE|VLC")) %>%
  adorn_totals(where = "col", name = "Sum_species.decontam") %>%
  mutate(Percent = Sum_species.decontam/sum(Sum_species.decontam)*100) %>%
  top_n(50, Percent) %>%
  select(-one_of("Sum_species.decontam","Percent")) %>%
  gather("SampleID","Counts",2:ncol(.)) %>%
  spread(SampleID,Counts) %>%
  select(Species) %>%
  mutate(JAE = 1)


# Now select only those species (top 50 of CMC, HMP, JAE) out of the table to create a new matrix
malt_species.decontam_top50_each_list <- malt_species.decontam_top50_cmcV %>%
  bind_rows(., malt_species.decontam_top50_hmpV) %>%
  bind_rows(., malt_species.decontam_top50_jaeV) %>%
  select(Species) %>%
  unique() %>%
  pull()

malt_species.decontam_top50_each <- malt_species.decontam %>%
  select(-one_of(outliers)) %>%
  select(-matches("SRR164|10M|EXB|LIB|ERR|SRS")) %>%
  filter(Species %in% malt_species.decontam_top50_each_list) %>%
  gather("SampleID","Counts",2:ncol(.)) %>%
  mutate(Counts = Counts + 1) %>%
  spread(Species,Counts) %>%
  column_to_rownames("SampleID")

# 88 of 150 species are left after unique() - how many species are in the top 50 of all 3 (22)? of JAE and HMP ()? of CMC and JAE ()? of CMC and HMP ()?
all3 <- malt_species.decontam_top50_cmcV %>%
  full_join(., malt_species.decontam_top50_jaeV) %>%
  full_join(., malt_species.decontam_top50_hmpV) %>%
  replace(is.na(.), 0) %>%
  adorn_totals(where = "col") %>%
  arrange(desc(Total), HMP, JAE, CMC)


# CLR-transform the matrix for plotting the heatmap
malt_species.decontam_top50_each_clr <- clr(malt_species.decontam_top50_each)
malt_species.decontam_top50_each_clr <- as.matrix(malt_species.decontam_top50_each_clr)

# orient the matrix with correct rows/columns to run the distance calculation for the species, not the samples (columns are SampleID, rows are Species)
malt_species.decontam_top50_each_clr_sp <- malt_species.decontam_top50_each_clr %>%
  as.data.frame() %>%
  rownames_to_column("SampleID") %>%
  gather("Species","Counts",2:ncol(.)) %>%
  spread(SampleID,Counts)

#add the rownames back
rownames(malt_species.decontam_top50_each_clr_sp) <- malt_species.decontam_top50_each_clr_sp$Species
malt_species.decontam_top50_each_clr_sp <- malt_species.decontam_top50_each_clr_sp %>% select(-Species)

# perform a distance calculation for hierarchical clustering for the species ordering
malt_species.decontam_top50_each_clr_dist <- vegdist(malt_species.decontam_top50_each_clr_sp, method = "euclidian")
# cluster the data with hclust
malt_species.decontam_top50_each_clr_dist_hr <- hclust(malt_species.decontam_top50_each_clr_dist)
# malt_species.decontam_top50_each_clr_dist_hr$order gives the dendrogram order from the bottom to the top, but using the row numbers not the row names
# pull this order out and store as a vector to make the order a factor in the next step for plotting
sp_each_order <- malt_species.decontam_top50_each_clr_dist_hr$order %>%
  as.character.numeric_version(.) %>%
  str_trim(.)

# use the dendrogram order to pull out the species in the correct order for the heatmap
malt_species.decontam_top50_each_clr_order <- malt_species.decontam_top50_each_clr %>%
  as.data.frame() %>%
  rownames_to_column("SampleID") %>%
  gather("Species","CLR",2:ncol(.)) %>%
  spread(SampleID,CLR) %>%
  mutate(SpOrder = as.character(seq(1,88))) %>%
  select(Species, SpOrder, everything()) %>%
  mutate(SpOrder = fct_relevel(SpOrder, sp_each_order)) %>%
  arrange(SpOrder) %>%
  pull(Species)

# make the species a factor so they're in the correct order for the heatmap using the vector from the step above
malt_species.decontam_top50_each_clr_long <- malt_species.decontam_top50_each_clr %>%
  as.data.frame() %>%
  rownames_to_column("SampleID") %>%
  gather("Species","CLR",2:ncol(.)) %>%
  spread(SampleID,CLR) %>%
  mutate(Species = fct_relevel(Species, malt_species.decontam_top50_each_clr_order)) %>%
  arrange(Species) %>%
  gather("SampleID","CLR", 2:ncol(.))

# now cluster by sample
# convert the matrix to a data.frame
malt_species.decontam_top50_each_clr_smp <- malt_species.decontam_top50_each_clr %>%
  as.data.frame()

# perform a distance calculation for hierarchical clustering for the species ordering
malt_species.decontam_top50_each_clr_smp_dist <- vegdist(malt_species.decontam_top50_each_clr_smp, method = "euclidian")
# cluster the data with hclust
malt_species.decontam_top50_each_clr_smp_dist_hr <- hclust(malt_species.decontam_top50_each_clr_smp_dist)
# malt_species.decontam_top50_each_clr_dist_hr$order gives the dendrogram order from the bottom to the top, but using the row numbers not the row names
# pull this order out and store as a vector to make the order a factor in the next step for plotting
smp_each_order <- malt_species.decontam_top50_each_clr_smp_dist_hr$order %>%
  as.character.numeric_version(.) %>%
  str_trim(.)

# use the dendrogram order to pull out the species in the correct order for the heatmap
malt_species.decontam_top50_each_clr_smp_order <- malt_species.decontam_top50_each_clr %>%
  as.data.frame() %>%
  rownames_to_column("SampleID") %>%
  gather("Species","CLR",2:ncol(.)) %>%
  spread(Species,CLR) %>%
  mutate(SmpOrder = as.character(seq(1,119))) %>%  
  select(SampleID, SmpOrder, everything()) %>%
  mutate(SmpOrder = fct_relevel(SmpOrder, smp_each_order)) %>%
  arrange(SmpOrder) %>%
  pull(SampleID)

# Plot the heatmap with samples ordered by the clustering from above
# make the SampleIDs a factor so they're in the correct order for the heatmap using the vector from the step above
malt_species.decontam_top50_each_clr_long <- malt_species.decontam_top50_each_clr %>%
  as.data.frame() %>%
  rownames_to_column("SampleID") %>%
  gather("Species","CLR",2:ncol(.)) %>%
  spread(SampleID,CLR) %>%
  mutate(Species = fct_relevel(Species, malt_species.decontam_top50_each_clr_order)) %>%
  arrange(Species) %>%
  gather("SampleID","CLR", 2:ncol(.)) %>%
  inner_join(., metadata %>%
               select(SampleID, Market_integration_split), by = "SampleID") %>%
  inner_join(., Market_integration_split_colors %>%
               as_data_frame(.) %>%
               rename(Color = value) %>%
               mutate(Market_integration_split = c("Logging road","Forest camp","Farming","Yanomami","Industrial plaque","Industrial calculus","ExtractionGauze","ExtractionBlank","LibraryBlank")), by = "Market_integration_split") %>%
  mutate(SampleID = fct_relevel(SampleID, malt_species.decontam_top50_each_clr_smp_order)) %>%
  arrange(SampleID)

vector_color = malt_species.decontam_top50_each_clr_long %>%
  select(SampleID, Color) %>%
  unique %>%
  pull(Color) %>%
  as.character()

# make a heatmap with ggplot
heatmap_base <- ggplot(malt_species.decontam_top50_each_clr_long, aes(SampleID, Species, fill = CLR)) +
  geom_tile() +
  scale_fill_viridis_c(option = "A") +
  theme_minimal(base_size = 12) +
  theme(axis.text.x = element_text(angle = 90, hjust = 0.95, color = vector_color),
        plot.margin = margin(0, 0, 0, 0, "pt"),
        axis.title.y = element_blank(),
        legend.position = "left")

heatmap_base


# Plot the heatmap with samples ordered by Village
# make the SampleIDs a factor so they're in the correct order for the heatmap using the vector from the step above
malt_species.decontam_top50_each_clr_long <- malt_species.decontam_top50_each_clr %>%
  as.data.frame() %>%
  rownames_to_column("SampleID") %>%
  gather("Species","CLR",2:ncol(.)) %>%
  spread(SampleID,CLR) %>%
  mutate(Species = fct_relevel(Species, malt_species.decontam_top50_each_clr_order)) %>%
  arrange(Species) %>%
  gather("SampleID","CLR", 2:ncol(.)) %>%
  inner_join(., metadata %>%
               select(SampleID, Village), by = "SampleID") %>%
  inner_join(., Village_colors %>%
               as_data_frame(.) %>%
               rename(Color = value) %>%
               mutate(Village = c("202","205","204","203","206","Industrial plaque","Industrial calculus","ExtractionGauze","ExtractionBlank","LibraryBlank")), by = "Village") %>%
  mutate(SampleID = fct_relevel(SampleID, each_order)) %>%
  arrange(SampleID)

vector_color = malt_species.decontam_top50_each_clr_long %>%
  select(SampleID, Color) %>%
  unique %>%
  pull(Color) %>%
  as.character()

# make a heatmap with ggplot
heatmap_xx3 <- ggplot(malt_species.decontam_top50_each_clr_long, aes(SampleID, Species, fill = CLR)) +
  geom_tile() +
  scale_fill_viridis_c(option = "A") +
  theme_minimal(base_size = 12) +
  theme(axis.text.x = element_text(angle = 90, hjust = 0.95, color = vector_color),
        plot.margin = margin(0, 0, 0, 0, "pt"),
        axis.title.y = element_blank(),
        legend.position = "left")

heatmap_xx3


# ggsave("./06-publication/main_figures/Figure_2/panel_parts/Figure_2_top50_sp_heatmap_clustered.pdf", plot = heatmap_xx3, device = "pdf",
#        scale = 1, width = 16, height = 13, units = c("in"), dpi = 300)

```

```{r}
# number of shared taxa
all3 %>% as_tibble(.) %>% filter(Total == 3) # 22 species

# number of CMC-HMP shared taxa
all3 %>% as_tibble(.) %>% filter(Total == 2, JAE == 0) # 8 species

# number of CMC-JAE shared taxa
all3 %>% as_tibble(.) %>% filter(Total == 2, HMP == 0) # 7 species

# number of HMP-JAE shared taxa
all3 %>% as_tibble(.) %>% filter(Total == 2, CMC == 0) # 0 species

# number of unshared taxa in CMC
all3 %>% as_tibble(.) %>% filter(Total == 1, CMC == 1) # 13 species

# number of unshared taxa in HMP
all3 %>% as_tibble(.) %>% filter(Total == 1, HMP == 1) # 17 species

# number of unshared taxa in JAE
all3 %>% as_tibble(.) %>% filter(Total == 1, JAE == 1) # 18 species

all3 %>%
  fwrite(., "./06-publication/supplemental_tables/abundant_species_overlap.tsv", quote = F, sep = "\t")

# Now genera - 37  total
all3 %>% as_tibble(.) %>% separate(Species, into = c("genus","species"), extra = "merge") %>%
  select(-species)

# note [Eubacterium] gets an empty cell here
all3_genera <- malt_species.decontam_top50_cmcV %>%
  separate(Species, into = c("genus","species"), extra = "merge") %>%
  select(-species) %>%
  distinct() %>%
  full_join(., malt_species.decontam_top50_jaeV %>%
  separate(Species, into = c("genus","species"), extra = "merge") %>%
  select(-species) %>%
  distinct()) %>%
  full_join(., malt_species.decontam_top50_hmpV %>%
  separate(Species, into = c("genus","species"), extra = "merge") %>%
  select(-species) %>%
  distinct()) %>%
  replace(is.na(.), 0) %>%
  adorn_totals(where = "col") %>%
  as_tibble() %>%
  arrange(desc(Total))

# number of shared genera
all3_genera %>% as_tibble(.) %>% filter(Total == 3) # 37 genera

# number of CMC-HMP shared taxa
all3_genera %>% as_tibble(.) %>% filter(Total == 2, JAE == 0) # 5 genera

# number of CMC-JAE shared taxa
all3_genera %>% as_tibble(.) %>% filter(Total == 2, HMP == 0) # 7 species

# number of HMP-JAE shared taxa
all3_genera %>% as_tibble(.) %>% filter(Total == 2, CMC == 0) # 0 species

# number of unshared taxa in CMC
all3_genera %>% as_tibble(.) %>% filter(Total == 1, CMC == 1) # 13 species

# number of unshared taxa in HMP
all3_genera %>% as_tibble(.) %>% filter(Total == 1, HMP == 1) # 17 species

# number of unshared taxa in JAE
all3_genera %>% as_tibble(.) %>% filter(Total == 1, JAE == 1) # 18 species


```


